# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    admin.collection_item:
        class: AppBundle\Admin\CollectionItemAdmin
        arguments: [~, AppBundle\Entity\CollectionItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Записи }

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Користувачі }

    admin.collection_type:
        class: AppBundle\Admin\CollectionTypeAdmin
        arguments: [~, AppBundle\Entity\CollectionType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Типи колекціі }

    admin.item_type:
        class: AppBundle\Admin\ItemTypeAdmin
        arguments: [~, AppBundle\Entity\ItemType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Жанри }

    admin.translation:
        class: AppBundle\Admin\TranslationAdmin
        arguments: [~, AppBundle\Entity\Translation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Переклади }

    admin.resolution:
        class: AppBundle\Admin\ResolutionAdmin
        arguments: [~, AppBundle\Entity\Resolution, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Якість }
